# Generated by Django 5.1.2 on 2024-10-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n_air', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='images/default-image.jpg', null=True, upload_to='category_images/'),
        ),
    ]
